api = "0.2"

[buildpack]
id = "projectriff/node-function-buildpack"
name = "Riff Node Function Buildpack"
version = "0.0.1"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "io.buildpacks.stacks.bionic"
